version: "1"
rules:
  - base: Build-stable-12
    upstream: pfsense:stable/12
    mergeMethod: merge
  - base: Build-12.1-clean
    upstream: pfsense:releng/12.1
    mergeMethod: merge
label: "WeiBot pull "
